from datetime import UTC, datetime
from decimal import Decimal
from enum import Enum
from typing import TYPE_CHECKING
from uuid import UUID, uuid4

from sqlalchemy import DateTime, ForeignKey, Numeric, String, text
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ...schemas.enums import Environment, IncidentSeverity
from .base import Base

if TYPE_CHECKING:
    from .incident import Incident
    from .service import Service


def enum_values(enum_class: type[Enum]) -> list[str]:
    return [member.value for member in enum_class]


class Alert(Base):
    """
    Database model representing an alert generated by a monitoring system.
    """

    __tablename__ = "alerts"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
    )

    service_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(
            "services.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    incident_id: Mapped[UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(
            "incidents.id",
            ondelete="RESTRICT",
        ),
        nullable=True,
        index=True,
    )

    environment: Mapped[Environment] = mapped_column(
        ENUM(
            Environment,
            name="environment_enum",
            create_type=False,
            values_callable=enum_values,
        ),
        nullable=False,
    )

    severity: Mapped[IncidentSeverity] = mapped_column(
        ENUM(
            IncidentSeverity,
            name="incident_severity_enum",
            create_type=False,
            values_callable=enum_values,
        ),
        nullable=False,
    )

    source: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    metric: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    value: Mapped[Decimal] = mapped_column(
        Numeric(20, 6),
        nullable=False,
    )

    threshold: Mapped[Decimal] = mapped_column(
        Numeric(20, 6),
        nullable=False,
    )

    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )

    fingerprint: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        unique=True,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=lambda: datetime.now(UTC),
    )

    incident: Mapped["Incident | None"] = relationship(
        back_populates="alerts",
    )

    service: Mapped["Service"] = relationship(
        back_populates="alerts",
    )
