"""add account lockout fields

Revision ID: 21051cc86b2a
Revises: 1eaedc0f2c41
Create Date: 2026-09-29 12:23:29.379652

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21051cc86b2a"
down_revision: str | Sequence[str] | None = "1eaedc0f2c41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "failed_login_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.add_column("users", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failed_login_attempts")
    # ### end Alembic commands ###
