"""add incident status

Revision ID: ac860e81dadf
Revises: d72025d4022a
Create Date: 2026-09-30 17:18:31.536455

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac860e81dadf"
down_revision: str | Sequence[str] | None = "d72025d4022a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    incident_status_enum = postgresql.ENUM(
        "open",
        "acknowledged",
        "resolved",
        name="incident_status_enum",
    )

    incident_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "incidents",
        sa.Column(
            "status",
            incident_status_enum,
            server_default="open",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incidents", "status")

    incident_status_enum = postgresql.ENUM(
        "open",
        "acknowledged",
        "resolved",
        name="incident_status_enum",
    )

    incident_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
