"""make alert fingerprint unique

Revision ID: d16d39e17a20
Revises: ac860e81dadf
Create Date: 2026-09-30 18:06:00.176878

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d16d39e17a20"
down_revision: str | Sequence[str] | None = "ac860e81dadf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_fingerprint"), table_name="alerts")
    op.create_index(op.f("ix_alerts_fingerprint"), "alerts", ["fingerprint"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_fingerprint"), table_name="alerts")
    op.create_index(op.f("ix_alerts_fingerprint"), "alerts", ["fingerprint"], unique=False)
    # ### end Alembic commands ###
